pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git branch: 'SamiGuezmir',
                    url: 'https://github.com/3ammarllii/5Gamix-GestionSkieur.git'
            }
        }
        stage('Build') {
            steps {
                dir('5Gamix-GestionSkieur-master') {
                    sh 'mvn install -Dmaven.test.skip=true'
                }
            }
        }
        /*stage('Test') {
            steps {
                sh 'mvn test'
            }
        }*/
    }
    post {
        success {
            echo 'Build finished successfully!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
